var configuration = {
    host: host,
    dynamicServiceName: "",
    title: "高级专题",
    initialMaps: [0],
    maps:
        [
            {
                Title: "主地图",
                OverviewImage: "/img/topics/家纺城区块招商引资地块示意图.jpg",
                LegendImage: "/img/legends/01-核心专题图件.jpg",
                FullExtent: { xmin: 40533555, ymin: 3370866, xmax: 40534347, ymax: 3371956 },
                Basemaps:
                    [
                        {
                            Id: 0,
                            Name: "遥感影像",
                            Title: "遥感影像",
                            IndexInService: 1,
                            TileServiceName: "Raster",
                            Editable: false,
                            ShowPicture: false,
                            PictureEditable: false,
                            Visible: true,
                            Alpha: 255
                        },
                        {
                            Id: 1,
                            Name: "土地利用",
                            Title: "土地利用",
                            IndexInService: 8,
                            TileServiceName: "DLTB",
                            Editable: false,
                            ShowPicture: false,
                            PictureEditable: false,
                            Visible: false,
                            Alpha: 255

                        },
                        {
                            Id: 2,
                            Name: "土地规划",
                            Title: "土地规划",
                            IndexInService: 38,
                            TileServiceName: "GHYT",
                            Editable: false,
                            ShowPicture: false,
                            PictureEditable: false,
                            Visible: false,
                            Alpha: 255
                        },
                        {
                            Id: 3,
                            Name: "控规",
                            Title: "控规",
                            IndexInService: 1,
                            TileServiceName: "KG",
                            Editable: false,
                            ShowPicture: false,
                            PictureEditable: false,
                            Visobale: false,
                            Alpha: 255
                        },
                        {
                            Id: 4,
                            Name: "总规",
                            Title: "总规",
                            IndexInService: 1,
                            TileServiceName: "ZG",
                            Editable: false,
                            ShowPicture: false,
                            PictureEditable: false,
                            Visobale: false,
                            Alpha: 255
                        }
                    ],
                Categories:
                    [
                        {
                            Id: 1,
                            Name: "地图1",
                            Visible: true,
                            Layers:
                                [
                                    {
                                        Id: 1,
                                        Name: "标注",
                                        Title: "标准",
                                        IndexInService: 1,
                                        TileServiceName: "",
                                        Editable: true,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        Symbol: {
                                            FillColor: { R: 255, G: 0, B: 0, A: 0 },
                                            OutlineColor: { R: 0, G: 255, B: 197, A: 1 }
                                        },
                                        CategoryId: 1,
                                        MinScale:10000
                                    },
                                    {
                                        Id: 2,
                                        Name: "用地信息",
                                        Title: "用地信息",
                                        IndexInService: 1,
                                        TitleServiceName: "GHYT",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1,
                                    },
                                    {
                                        Id: 3,
                                        Name: "其他相关控规分析",
                                        Title: "其他相关控规分析",
                                        IndexInService: 1,
                                        TitleServiceName: "Raster",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1,
                                    },
                                    {
                                        Id: 4,
                                        Name: "地价数据",
                                        Title: "地价数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId:1
                                    },
                                    {
                                        Id: 5,
                                        Name: "地籍地形数据",
                                        Title: "地籍地形数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1
                                    },
                                    {
                                        Id: 6,
                                        Name: "基础地理数据",
                                        Title: "基础地理数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1
                                    },
                                    {
                                        Id: 7,
                                        Name: "基础现状",
                                        Title: "基础现状",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1
                                    },
                                    {
                                        Id: 8,
                                        Name: "土地规划",
                                        Title: "土地规划",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1
                                    },
                                    {
                                        Id: 9,
                                        Name: "城镇总体规划及控规",
                                        Title: "城镇总体规划及控规",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 1
                                    }
                                ]
                        },
                        {
                            Id: 2,
                            Name: "地图2",
                            Visible: true,
                            Layers:
                                [
                                    {
                                        Id: 10,
                                        Name: "标注",
                                        Title: "标准",
                                        IndexInService: 1,
                                        TileServiceName: "",
                                        Editable: true,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        Symbol: {
                                            FillColor: { R: 255, G: 0, B: 0, A: 0 },
                                            OutlineColor: { R: 0, G: 255, B: 197, A: 1 }
                                        },
                                        CategoryId: 2,
                                        MinScale: 10000
                                    },
                                    {
                                        Id: 11,
                                        Name: "用地信息",
                                        Title: "用地信息",
                                        IndexInService: 1,
                                        TitleServiceName: "GHYT",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2,
                                    },
                                    {
                                        Id: 12,
                                        Name: "其他相关控规分析",
                                        Title: "其他相关控规分析",
                                        IndexInService: 1,
                                        TitleServiceName: "Raster",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2,
                                    },
                                    {
                                        Id: 13,
                                        Name: "地价数据",
                                        Title: "地价数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    },
                                    {
                                        Id: 14,
                                        Name: "地籍地形数据",
                                        Title: "地籍地形数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    },
                                    {
                                        Id: 15,
                                        Name: "基础地理数据",
                                        Title: "基础地理数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    },
                                    {
                                        Id: 16,
                                        Name: "基础现状",
                                        Title: "基础现状",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    },
                                    {
                                        Id: 17,
                                        Name: "土地规划",
                                        Title: "土地规划",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    },
                                    {
                                        Id: 18,
                                        Name: "城镇总体规划及控规",
                                        Title: "城镇总体规划及控规",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 2
                                    }
                                ]
                        },
                        {
                            Id: 3,
                            Name: "地图3",
                            Visible: true,
                            Layers:
                                [
                                    {
                                        Id: 19,
                                        Name: "标注",
                                        Title: "标准",
                                        IndexInService: 1,
                                        TileServiceName: "",
                                        Editable: true,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        Symbol: {
                                            FillColor: { R: 255, G: 0, B: 0, A: 0 },
                                            OutlineColor: { R: 0, G: 255, B: 197, A: 1 }
                                        },
                                        CategoryId: 3,
                                        MinScale: 10000
                                    },
                                    {
                                        Id: 20,
                                        Name: "用地信息",
                                        Title: "用地信息",
                                        IndexInService: 1,
                                        TitleServiceName: "GHYT",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3,
                                    },
                                    {
                                        Id: 21,
                                        Name: "其他相关控规分析",
                                        Title: "其他相关控规分析",
                                        IndexInService: 1,
                                        TitleServiceName: "Raster",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3,
                                    },
                                    {
                                        Id: 22,
                                        Name: "地价数据",
                                        Title: "地价数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    },
                                    {
                                        Id: 23,
                                        Name: "地籍地形数据",
                                        Title: "地籍地形数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    },
                                    {
                                        Id: 24,
                                        Name: "基础地理数据",
                                        Title: "基础地理数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    },
                                    {
                                        Id: 25,
                                        Name: "基础现状",
                                        Title: "基础现状",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    },
                                    {
                                        Id: 26,
                                        Name: "土地规划",
                                        Title: "土地规划",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    },
                                    {
                                        Id: 27,
                                        Name: "城镇总体规划及控规",
                                        Title: "城镇总体规划及控规",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 3
                                    }
                                ]
                        },
                        {
                            Id: 4,
                            Name: "地图4",
                            Visible: true,
                            Layers:
                                [
                                    {
                                        Id: 28,
                                        Name: "标注",
                                        Title: "标准",
                                        IndexInService: 1,
                                        TileServiceName: "",
                                        Editable: true,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        Symbol: {
                                            FillColor: { R: 255, G: 0, B: 0, A: 0 },
                                            OutlineColor: { R: 0, G: 255, B: 197, A: 1 }
                                        },
                                        CategoryId: 4,
                                        MinScale: 10000
                                    },
                                    {
                                        Id: 29,
                                        Name: "用地信息",
                                        Title: "用地信息",
                                        IndexInService: 1,
                                        TitleServiceName: "GHYT",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: true,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4,
                                    },
                                    {
                                        Id: 30,
                                        Name: "其他相关控规分析",
                                        Title: "其他相关控规分析",
                                        IndexInService: 1,
                                        TitleServiceName: "Raster",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4,
                                    },
                                    {
                                        Id: 31,
                                        Name: "地价数据",
                                        Title: "地价数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    },
                                    {
                                        Id: 32,
                                        Name: "地籍地形数据",
                                        Title: "地籍地形数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    },
                                    {
                                        Id: 33,
                                        Name: "基础地理数据",
                                        Title: "基础地理数据",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    },
                                    {
                                        Id: 34,
                                        Name: "基础现状",
                                        Title: "基础现状",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    },
                                    {
                                        Id: 35,
                                        Name: "土地规划",
                                        Title: "土地规划",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    },
                                    {
                                        Id: 36,
                                        Name: "城镇总体规划及控规",
                                        Title: "城镇总体规划及控规",
                                        IndexInService: 1,
                                        TitleServiceName: "",
                                        Editable: false,
                                        ShowPicture: false,
                                        PictureEditable: false,
                                        Annotation: false,
                                        Visible: true,
                                        Alpha: 1,
                                        CategoryId: 4
                                    }
                                ]
                        }
                    ]
            }
        ]
};

var application = new MapApplication(
    configuration,
    "mapsetContainer", "mapTemplate", "overviewDiv", "overviewTemplateDiv"
);
